### ISSUE TITLE
请问单主机无GPU如何设置参数？

### ISSUE THREAD

**Issue by imamtom** [csl-cqu/Roubst-and-Privacy-preserving-Federated-Learning-System#1]
我在\spfl_experiments\distributed\fedavg\GPU_MAPPING.md中看

> Note: If you do not pass `gpu_mapping.yaml` into `main.py`, all processes will use CPU.

但是`main_fedavg.py`默认会传入`gpu_mapping.yaml`。请问我想在本机（只有CPU）训练，该如何传入参数？

**Comment by LuckMonkeys** [comment]
将 main_fedavg.py 中的 gpu_mapping_file 参数的默认值删除，调用 main_fedavg.py 时不传入 gpu_mapping_file 参数。

对于 gpu_mapping_file 的处理函数为：  
![image](https://user-images.githubusercontent.com/34481971/137840202-0cd48b9f-bc3b-4733-b8bc-18d41665f811.png)
如果参数 gpu_mapping_file 为None， 则使用 CPU
